name: Install Test

on:
  push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    
    - name: Download TGZ
      run: |
        curl -o temp.zip https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/1.27.2/zowe-cli-package-1.27.2.zip
        unzip temp.zip
    
    - name: Update NPM
      run: npm install -g npm@8.5.5
    
    - name: Configure Invalid Proxy
      run: npm config set -g proxy http://proxy.invalid

    - name: Install TGZ Offline
      run: npm install -g zowe-cli.tgz --loglevel=silly
