name: Install Test

on:
  push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    
    - name: Setup Invalid Proxy
      run: npm config set -g proxy INVALID_PROXY

    - name: Install TGZ Offline
      run: npm install -g npm-offline-test-1.0.0.tgz
